/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_constants.h"

namespace storage {

const storageConstants g_storage_constants;

storageConstants::storageConstants() {
}

} // namespace

