/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "client_constants.h"

namespace librbd {

const clientConstants g_client_constants;

clientConstants::clientConstants() {
}

} // namespace

