/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef client_CONSTANTS_H
#define client_CONSTANTS_H

#include "client_types.h"

namespace librbd {

class clientConstants {
 public:
  clientConstants();

};

extern const clientConstants g_client_constants;

} // namespace

#endif
