/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef migrater_CONSTANTS_H
#define migrater_CONSTANTS_H

#include "migrater_types.h"

namespace tutorial {

class migraterConstants {
 public:
  migraterConstants();

};

extern const migraterConstants g_migrater_constants;

} // namespace

#endif
