// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Migrater.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::tutorial;

class MigraterHandler : virtual public MigraterIf {
 public:
  MigraterHandler() {
    // Your initialization goes here
  }

  int32_t migrate(const int32_t num1, const std::vector<std::string> & list1) {
    // Your implementation goes here
    printf("migrate\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MigraterHandler> handler(new MigraterHandler());
  shared_ptr<TProcessor> processor(new MigraterProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

