/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "migrater_constants.h"

namespace tutorial {

const migraterConstants g_migrater_constants;

migraterConstants::migraterConstants() {
}

} // namespace

