/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef storage_CONSTANTS_H
#define storage_CONSTANTS_H

#include "storage_types.h"

namespace storage {

class storageConstants {
 public:
  storageConstants();

};

extern const storageConstants g_storage_constants;

} // namespace

#endif
