/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef monitor_CONSTANTS_H
#define monitor_CONSTANTS_H

#include "monitor_types.h"

namespace monitor {

class monitorConstants {
 public:
  monitorConstants();

};

extern const monitorConstants g_monitor_constants;

} // namespace

#endif
