/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "monitor_constants.h"

namespace monitor {

const monitorConstants g_monitor_constants;

monitorConstants::monitorConstants() {
}

} // namespace

