// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MonitorServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::monitor;

class MonitorServerHandler : virtual public MonitorServerIf {
 public:
  MonitorServerHandler() {
    // Your initialization goes here
  }

  int32_t lock_and_get_pool(const std::string& eid) {
    // Your implementation goes here
    printf("lock_and_get_pool\n");
  }

  void release_lock(const std::string& eid) {
    // Your implementation goes here
    printf("release_lock\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MonitorServerHandler> handler(new MonitorServerHandler());
  shared_ptr<TProcessor> processor(new MonitorServerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

