// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MonitorService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::monitor;

class MonitorServiceHandler : virtual public MonitorServiceIf {
 public:
  MonitorServiceHandler() {
    // Your initialization goes here
  }

  void finish_lock(const std::string& eid) {
    // Your implementation goes here
    printf("finish_lock\n");
  }

  void report_client_info(const ClientInfo& ci) {
    // Your implementation goes here
    printf("report_client_info\n");
  }

  void finish_migration(const std::string& eid) {
    // Your implementation goes here
    printf("finish_migration\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MonitorServiceHandler> handler(new MonitorServiceHandler());
  shared_ptr<TProcessor> processor(new MonitorServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

